"""
Django settings for coolsite project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # Путь к базовой (рабочей) директории этого проекта.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jyjgf=11hzym(mw+u2kw=z45ph26d8z-0e8ail!v4jus@971(q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Состояние режима отладки. True - включен. Отключать,т.е. False, когда на боевом сервере.
# Если False, тогда нужно в ALLOWED_HOSTS добавить адрес(а).

ALLOWED_HOSTS = ['localhost', '127.0.0.1', ]  # Разрешенные адреса.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'women.apps.WomenConfig',  # В дальнейшем это позволит упростить работу с админкой. Но можно и просто 'women'.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coolsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'women.context_processors.statistics',  # Теперь можно использовать эти данные в любом шаблоне!
            ],
        },
    },
]

WSGI_APPLICATION = 'coolsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Указан драйвер СУБД, которую мы используем.
        'NAME': BASE_DIR / 'db.sqlite3',  # Путь к файлу базы данных.
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru'  # Язык всего фреймворка, в частности админ-панели.

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'  # Префикс, который будет добавляться к URL-адресам статических файлов.
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Путь к общей папке, куда будут собираться все статические файлы, когда сайт будет на боевом сервере.
STATICFILES_DIRS = []  # Список нестандартных путей к статическим файлам (если такие есть).

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Здесь указан путь к директории, куда будут загружаться изображения.
MEDIA_URL = '/media/'  # К url-адресам изображений будет будет добавляться следующий префикс: '/media/'.
